spring.application.name=ShopKart
server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommerce}
spring.datasource.username=${DB_USERNAME:springstudent}
spring.datasource.password=${DB_PASSWORD:springstudent}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


jwt.secret=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz12
jwt.expiration=3600000



razorpay.key_id=rzp_test_So4zRTYiAGVK6s
razorpay.key_secret=CEjQ3Hy1UEiRYYO97eBYl7C6